services:
  hh-applicant-tool:
    container_name: hh_applicant_tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    # environment:
    #   - TZ=Europe/Moscow
